### ISSUE TITLE
RGB settings

### ISSUE THREAD

**Issue by Dimarv135** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#24]
Always fc after v4.0. pixel 2 xl running latest pie.

**Comment by franciscofranco** [comment]
I fixed it in a later build, so make sure you're using the latest.

**Comment by Dimarv135** [comment]
I reported the bug with version 4.0.2 and I don't see a newer one available. I still can't open rgb settings.

**Comment by franciscofranco** [comment]
That's pretty odd. I'll re-open this and check it out.

**Comment by franciscofranco** [comment]
I couldn't reproduce on any device, but I looked at the stacktrace and made some changes which should prevent this from happening. Once 4.1 is out let me know and if the issue persists please re-open this.

**Comment by Dimarv135** [comment]
Issue is fixed for me on latest update.

**Comment by franciscofranco** [comment]
Thanks for the heads-up.
