### ISSUE TITLE
Big little cluster detection (?)

### ISSUE THREAD

**Issue by zputnyq** [franciscofranco/FK-Kernel-Manager-IssuesAndFeatureRequest#94]
![Screenshot_20190717-212237](https://user-images.githubusercontent.com/31039796/61384591-1ed39e00-a8db-11e9-9bc3-a1e71008c6c2.png)
![Screenshot_20190717-212144](https://user-images.githubusercontent.com/31039796/61384604-26934280-a8db-11e9-90b6-f003d40076db.png)

Hi @franciscofranco 

I'm new user of FK kernel manager.
It's confusing that I found out about big little cluster detection is different to Kernel Adiutor, on FK, it's showing the opposite of KA. I don't know whether it's a bug or not. I hope you don't mind looking at it.
I'm on xperia m4 aqua (SD 615) stock rom 6.0.1 & stock kernel.

Thanks, 
I really appreciate it

**Comment by franciscofranco** [comment]
I have absolutely no idea how that's even possible :/

**Comment by gandalf02** [comment]
Yes sir , it's possible , cause some Snapdragon chipsets have 0-3 as little CPUs , and 4-7 as big unlike the generic ones ,like sdm435 . May be kernel auditor has a different algo for detecting the big and little clusters. Or may be u implemented big and little core algo by just taking 0-3 as big and 4-7 as little like all other socs like 8996 have.

**Comment by gandalf02** [comment]
> I have absolutely no idea how that's even possible :/

Yes sir , it's possible , because some Snapdragon chipsets have 0-3 as big CPUs , and 4-7 as little like sdm435 . May be kernel auditor has a different algo for detecting the big and little clusters. Or may be u implemented big and little core detection algo by just taking 0-3 as little and 4-7 as big(for 4 cores 0-1 are little and 2-3 big ) like all other socs like 8996 have.

**Comment by franciscofranco** [comment]
@kdrag0n gave me a good idea to tackle this. I'll ship it for 4.4.1 or something, currently no time to work it out for 4.4.

**Comment by franciscofranco** [comment]
Should be working fine now. Re-open if not.

**Comment by zputnyq** [comment]
Still the same on 4.5.1 & 4.6
![Screenshot_20190906-132224](https://user-images.githubusercontent.com/31039796/64405574-b23e7980-d0a9-11e9-9a4d-9826eb2282a0.png)
![Screenshot_20190906-131926](https://user-images.githubusercontent.com/31039796/64405595-bc607800-d0a9-11e9-9490-1032369f56f0.png)

**Comment by franciscofranco** [comment]
Shit :)

**Comment by franciscofranco** [comment]
It's been fixed.
